sudo: required
services:
  - docker

before_install:
  - docker build -t itsvelikov/docker-learning -f Dockerfile.dev .

script:
  - docker run -e CI=true itsvelikov/docker-learning mvn test

after_success:
  - docker build -t itsvelikov/docker-learning -f Dockerfile .
# Logging in to the docker CLI
# first part retrieves pass from travis env and supply is an input for the next part of command
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Take image and push it to the docker hub
  - docker push itsvelikov/docker-learning

#deploy:
#  provider: elasticbeanstalk
#  region: "eu-central-1"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-eu-central-1-951562419135"
#  bucket_path: "docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY