version: '3'
services:
  redis-server:
    image: 'redis'
  counter-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/app/src
    ports:
      - "8080:5000"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/app/src
    command: [ "mvn", "test" ]