version: '3'
services:
  postgres:
    image: 'postgres:latest'
#  redis-server:
#    image: 'redis'
#    ports:
#      - "6379:6379"
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=postgres
#  fib-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"