version: '3'
services:
  redis-server:
    image: 'redis'
    ports:
      - "6379:6379"
  postgres:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
#  counter-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"