version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
  redis-server:
    image: 'redis:latest'
  fib-app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - ./src:/usr/app/src
    environment:
      - APP_PORT=5000
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgresql
      - POSTGRES_PORT=5432
    ports:
      - "8080:5000"
    depends_on:
      - postgres
      - redis-server

#postgres aws rds settings : username:postgres   password: postgrespassword