server:
  port: 5000
spring:
  redis:
    port: 6379
    host: redis-server
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: password