server:
  port: ${APP_PORT}
spring:
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}
  jpa:
    database: ${POSTGRES_DB}
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:${POSTGRES_DB}://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_USER}
    #    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  flyway:
    url: jdbc:${POSTGRES_DB}://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_USER}
    #    url: jdbc:postgresql://localhost:5432/postgres
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}